parameters:
  - name: deployment_environment
    displayName: Environment
    values:
      - DEV
      - UAT

variables:
  - group: APIM_AUTOMATION
  - ${{ if eq(parameters.deployment_environment, 'DEV') }}:
      - group: DEV_SETTINGS_ESLZ
  - ${{ if eq(parameters.deployment_environment, 'UAT') }}:
      - group: UAT_SETTINGS

jobs:
- job: APIM_IAC
  timeoutInMinutes: 180
  pool:
    vmImage: ubuntu-latest

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g tfx-cli
      displayName: 'Install TFX CLI'

    - script: |
        npm install -g terraform
      displayName: 'Install Terraform'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SERVICE_CONNECTION_AZURE)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform --version
      displayName: 'Check Terraform Version'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SERVICE_CONNECTION_AZURE)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform init -backend-config="$(BACKEND_FILE)"
      displayName: 'Terraform Init'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SERVICE_CONNECTION_AZURE)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform validate
      displayName: 'Terraform Validate'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SERVICE_CONNECTION_AZURE)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform plan -var-file="$(VARIABLES_FILE)"
      displayName: 'Terraform Plan'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(SERVICE_CONNECTION_AZURE)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform apply -var-file="$(VARIABLES_FILE)" -auto-approve
      displayName: 'Terraform Apply'